name: SyncGiteeRapidOcrCppToGitHub
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Gitee → GitHub
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'gitee/RapidAI'          # 只写 组织
          dst: 'github/RapidAI'         # 只写 组织
          static_list: 'RapidOcrCpp'    # 只同步这一个仓库

          dst_key: ${{ secrets.AUTO_GITEE_TO_GITHUB_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITHUB_TOKEN }}

          account_type: org
          force_update: true
          debug: true
