name: SyncGitHubToGitee
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 14 * * *'  # 每天 22:00 同步
  workflow_dispatch:     # 允许手动触发

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 获取仓库列表：排除私有
      - name: Get repo list
        id: repo
        uses: yi-Xu-0100/repo-list-generator@v1.1.1

      # 同步：GitHub 组织 → Gitee 组织
      - name: Mirror to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/RapidAI'
          dst: 'gitee/RapidAI'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          force_update: true
          account_type: org
          debug: true
          # 同步：非私有仓库（public + 非fork）
          static_list: ${{ steps.repo.outputs.repoList }}
          # 黑名单：不同步的仓库
          black_list: ".github,rapidai.github.io,RapidOCR,llama-dl"
