name: SyncToGitee
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/SyncToGitee.yml'
  schedule:
    - cron: '0 14 * * *'  # 每天22点运行 14 + 8


jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v3

      - name: Get repository list exclude private and fork
        id: repo
        uses: yi-Xu-0100/repo-list-generator@v1.0.1

      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/RapidAI'
          dst: 'gitee/RapidAI'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          force_update: true
          account_type: org
          debug: true
          static_list: ${{ steps.repo.outputs.repoList }}  # 仅同步非private，非fork的仓库
          black_list: ".github,rapidai.github.io "
